export const SCREEN_CONSTANT = {
  ONBOARDING:'OnBoarding',
  SPLASH:'Splash',
  LANGUAGE:'language',
  LANGUAGESET:'languageApp',
  LOG_IN: 'login',
  INVITE:'InviteFriends',
  OTP:'VerifyOTP',
  SIGN_UP: 'signup',
  FORGOT_PASSWORD: 'forgotPassword',
  HOME: 'home',
  MESSAGES:'Messages',
  FAV:'Favorites',
  PROFILE:'Profile',
  USER_SUPPORT:'UserSupport',
  CONTACT_US:'ContactUs',
  USER_SUPPORT_CATEGORY:'UserSupportCategory',
  USER_SUPPORT_CATEGORY_QUERIES:'UserSupportCategoryQueries',
  CHAT:'Chat',
  WALLET:'Wallet',
  OFFERS:'Offers',
  PASSES:'Passes',
  BE_A_LISTENER:'BeListener',
  PAYMENT_DETAILS_LISTENER:'PaymentDetailsListener',
  AUTO_CONNECT:'AutoConnect',
  LISTENER_PROFILE:'ListenerProfile',
  EDIT_PROFILE:'EditProfile',
  DASHBOARD:'Dashboard',
  COMPLETE_PROFILE:'CompleteProfile',
  RATING_CALL:'RatingCall',
  SEARCH:'Search',
  GIFT_LISTENER:'GiftListener',
  INVITE_LISTENER:'InviteFriendsListener',
  INCOMING_CALL:'IncomingCall'


};
