export default {
    ble: "a",
    camSwipe: "b",
    info: "c",
    message: "d",
    report: "e",
    earn: "f",
    logout: "g",
    filter: "h",
    share: "i",
    language: "j",
    lang: "j",
    delete: "k",
    mobScr: "m",
    security: "n",
    rupee: "o",
    down: "p",
    right: "q",
    setting: "r",
    back: "s",
    listen: "t",
    bell: "u",
    vert: "v",
    secure: "w",
    dot: "x",
    user: "y",
    terms: "z",
    switch: 'A',
    support: 'B',
    mute: 'C',
    phone: 'D',
    video:'9',
    copy:'6',
    wallet: 'E',
    speaker: 'F',
    starEmpty: 'G',
    starF: 'H',
    clock:'P',
    heart:'3',
    pen:'N',
    passport:'M',
    idCard:'O',
    license:'Q',
    vert:'v',
    radio:'T',
    radioF:'U',
    check:'W',
    search:'w',
    seen:'Y',
    verify:'l',
    send:'J',
    tab1:'S',
    edit:'R'
    


};
